<div class="row-fluid">
    <div class="box span24">
        <div class="box-header">
            <h2><?php echo $this->translate('My Discussions') ?></h2>
            <a href="<?php echo $this->url('add-my-discussion') ?>" class="pull-right text-warning"><?php echo $this->translate('New Discussion') ?></a>
        </div>

        <div class="box-content">

            <form action="<?php echo $this->url('do-bulk-action') ?>" method="POST">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th class="optional"></th>
                        <th><?php echo $this->translate('Discussion Title') ?></th>
                        <th class="optional"><?php echo $this->translate('Partial Description') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (empty($this->discussions)) : ?>
                    <tr>
                        <td colspan="3"><p class="no-record-found"><?php echo $this->translate('No discussion has been found.') ?></p></td>
                    </tr>
                    <?php else: foreach ($this->discussions AS $discussion) : ?>
                    <tr>
                        <td class="optional"><input type="checkbox" name='discussionIds[]' value="<?php echo $discussion['discussion_id'] ?>" /></td>
                        <td>
                            <a href='<?php echo $this->url('show-my-discussion', array('permalink' => $discussion['permalink'])) ?>'>
                                <?php echo $discussion['title'] ?></a>
                            <span class="label label-inverse"><?php echo $this->statuses[$discussion['discussion_status']] ?></span>
                        </td>
                        <td>
                            <?php echo $this->Discussion()->getShortSummaryWithLink($discussion, 50, 90, $this->translate('See Detail')) ?><br />
                            <span class="label label-inverse">
                                <small style="font-size: 12px;">
                                    <?php echo $this->BlogPost()->getCategoryLink($discussion, $this->categories, ', ') ?> <?php echo $this->translate('Division') ?>
                                    <span data-toggle="tooltip" title="<?php echo $this->DateTimeEnToBn()->ShowDate($discussion['discussion_created']) ?>"><?php echo $this->DateTimeEnToBn()->timeSince($discussion['discussion_created']) ?></span>
                                    <?php echo $this->translate('Written') ?>
                                </small>
                            </span>
                            <small style="margin-left: 10px">
                                <a href='<?php echo $this->url('edit-my-discussion', array('permalink' => $discussion['permalink'])) ?>'>
                                    <i class="icon icon-remove-sign"></i><?php echo $this->translate('Edit') ?></a>
                                <?php if ($discussion['discussion_status'] != \NBlog\Model\WritingStatus::PUBLISHED) : ?>

                                <?php switch ($discussion['discussion_status']) :
                                    case \NBlog\Model\WritingStatus::DRAFT: ?>
                                        &raquo;
                                        <a href='<?php echo $this->url('trash-my-discussion', array('permalink' => $discussion['permalink'])) ?>'>
                                            <i class="icon icon-remove-sign"></i><?php echo $this->translate('Remove') ?></a>

                                        <?php break;

                                    case \NBlog\Model\WritingStatus::TRASH: ?>
                                        &raquo;<a href='<?php echo $this->url('restore-my-discussion', array('permalink' => $discussion['permalink'])) ?>'><?php echo $this->translate('Restore This') ?></a>
                                        &raquo;<a href='<?php echo $this->url('delete-my-discussion', array('permalink' => $discussion['permalink'])) ?>'>
                                            <i class="icon icon-remove-sign"></i><?php echo $this->translate('Delete Permanently') ?></a>
                                        <?php break;
                                endswitch; endif ?>
                            </small>
                        </td>
                    </tr>
                    <?php endforeach; endif ?>
                    </tbody>
                </table>

                <?php if (!empty($this->discussions)) : ?>
                    <div class="pagination pagination-centered">
                        <?php echo $this->partial('blog-user/partials/bulk-actions') ?>
                        <?php echo $this->paginator()->slide($this->paginator, array_merge($this->paginatorOptions, array('linksOnly' => true, 'class' => 'pull-right'))) ?>
                    </div>
                <?php endif ?>
            </form>
            <div>
                <h3>কি-নোট: </h3>
                <ul class="nav-list unstyled">
                    <li><span class="label label-info">অপ্রকাশিত:</span> যে মুক্ত আলোচনাগুলি আপনি নিজে এখনো প্রকাশিত করেননি।</li>
                    <li><span class="label label-warning">ব্যানড্‌:</span> ব্লগ কর্তৃপক্ষ কোন না কোন কারণে মুক্ত আলোচনাটি বাতিল করেছেন।</li>
                    <li><span class="label label-inverse">রিপোর্টেড:</span> জনসাধারণ কর্তৃক মুক্ত আলোচনাটি একাধিকবার রিপোর্ট করা হয়েছে।</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    .box-content table th {
        background: #3B5990;
        border-left: #CCC 1px solid;
        color: #000;
    }
</style>