<?php $currentUser = $this->sessionContainer()->getData('user_id') ?>
<div class="box span24">
    <div class="box-header">
        <h2><i class="icon-bookmark icon-white"></i><?php echo $this->translate('Discussion Details') ?></h2>
        <?php if ($currentUser == $this->discussion['discussion_created_by']) : ?>
        <a href="<?php echo $this->url('edit-my-discussion', array('permalink' => $this->discussion['permalink'])) ?>"
           class="pull-right text-warning"><?php echo $this->translate('Update Discussion') ?></a>
        <?php endif ?>
    </div>

    <div class="box-content">
        <div class="single-post">
            <div class="post-header">
                <a href="#"><img src="<?php echo $this->Profile()->getImage($this->discussion) ?>"/></a>
                <h4 class="post-title"><?php echo $this->NBEscapeHtml($this->discussion['title']) ?></h4>
                <div class="post-details">
                    <?php echo $this->Post()->getSummaryPost($this->discussion, $this->categories, $this->professions, $this->discussion['published']) ?>
                </div>
            </div>

            <div class="post-body">
                <?php echo $this->NBEscapeHtml($this->discussion['details'], true) ?>
            </div>

            <div class="post-footer">
                <div class="post-actions">
                    <?php if (!isset($this->discussion['isBlocked']) && $this->discussion['discussion_status'] == \NBlog\Model\WritingStatus::PUBLISHED) : ?>
                        <a href='javascript: void(0)' class='do-comment-for-writing'><?php echo $this->translate('Write Comment') ?></a>
                    <?php endif ?>

                    <?php if ($currentUser == $this->discussion['discussion_created_by']) : ?>
                        <a href='<?php echo $this->url('edit-my-discussion', array('permalink' => $this->discussion['permalink'])) ?>'>
                            <?php echo $this->translate('Edit This') ?>
                        </a>
                        <a href='<?php echo $this->url('trash-my-discussion', array('permalink' => $this->discussion['permalink'])) ?>' class="trash">
                            <?php echo $this->translate('Make trash') ?>
                        </a>
                    <?php else : ?>
                        <?php echo $this->BlogPost()->getLinkToDealWithFavorite(
                            $this->discussion['permalink'], \BlogUser\Model\FavoriteType::DISCUSSION, isset($this->discussion['isFavorite']), false) ?>

                        <?php if (isset($this->discussion['hasUserReported'])) : ?>
                            <i class="icon icon-flag"></i> <?php echo $this->translate('Already Reported') ?>
                        <?php else : ?>
                            <a href="" class='do-report-on-writing' rel='<?php echo $this->discussion['discussion_id'] ?>'><?php echo $this->translate('Make a complaint') ?></a>
                        <?php endif ?>

                        <?php if (isset($this->discussion['isHidden'])) : ?>
                            <a href='<?php echo $this->url('unhide-my-blog-content', array('content_type'=>\NBlog\Model\WritingType::DISCUSSION,'permalink' => $this->discussion['permalink'])) ?>'><?php echo $this->translate('Display again') ?></a>
                        <?php else : ?>
                            <a href='<?php echo $this->url('hide-my-blog-content', array('content_type'=>\NBlog\Model\WritingType::DISCUSSION,'permalink' => $this->discussion['permalink'])) ?>'><?php echo $this->translate('Hide') ?></a>
                        <?php endif ?>
                    <?php endif?>

                    <a onClick="window.open('<?php echo $this->BlogPost()->facebookShare($this->discussion) ?>', 'feedDialog','toolbar=0,status=0,width=626,height=436')" href="javascript: void(0)">FB Share</a>
                </div>

                <div class="post-summary">
                    <span><i class="icon icon-comment"></i><a href="#"><span class="commentCount"><?php echo $this->number()->convert($this->discussion['total_comments']) ?></span></a></span>
                    <span><i class="icon-thumbs-up"></i><a href="#"><span class="likeCount"><?php echo $this->number()->convert($this->discussion['total_favorited']) ?></span></a></span>
                    <span><i class="icon-eye-open"></i><?php echo $this->number()->convert($this->discussion['total_viewed']) ?></span>
                </div>
            </div>

            <?php echo $this->partial('blog/partials/all-comments-view', array(
                'commentOn' => $this->discussion,
                'comments' => $this->comments,
                'creator' => $this->discussion['discussion_created_by'],
                'userDetails' => $this->userDetails,
                'commentFor' => \NBlog\Model\WritingType::DISCUSSION,
                'blockedBloggers' => $this->blockedBloggers,
                'isBlocked' => isset($this->discussion['isBlocked']),
                'isWritingReported' => isset($this->discussion['hasUserReported']),
                'commentForm' => $this->commentForm,
                'reportForm' => $this->reportForm
            )) ?>
        </div>
    </div>
</div>