<div class="box span24">
    <div class="box-header">
        <h2>
            <i class="icon-bookmark icon-white"></i><?php echo $this->translate('Mood Details') ?>
        </h2>
    </div>

    <div class="box-content">
        <div class="single-post">
            <div class="post-header">
                <a href="javascript: void(0)"><img src="<?php echo $this->Profile()->getImage($this->mood) ?>"/></a>
                <div class="post-title post-title-only">
                    <div style='height: 36px;'></div>
                </div>

                <div class="post-details">
                    <?php echo $this->Post()->getSummaryMood($this->mood, $this->professions, $this->mood['mood_updated']) ?>
                </div>
            </div>

            <div class="post-body">
                <?php echo $this->mood['title'] ?>
            </div>

            <div class="post-footer">
                <div class="post-actions">
                    <?php $currentUser = $this->sessionContainer()->getData('user_id') ?>
                    <?php if (!isset($this->mood['isBlocked']) && $this->mood['mood_status'] == \NBlog\Model\WritingStatus::PUBLISHED) : ?>
                        <a href='javascript: void(0)' class='do-comment-for-writing'><?php echo $this->translate('Write Comment') ?></a>
                    <?php endif ?>

                    <?php if ($currentUser == $this->mood['mood_created_by']) : ?>
                        <a href='<?php echo $this->url('edit-my-mood', array('permalink' => $this->mood['permalink'])) ?>'>
                            <?php echo $this->translate('Edit This') ?>
                        </a>
                        <a href='<?php echo $this->url('trash-my-mood', array('permalink' => $this->mood['permalink'])) ?>' class="trash">
                            <?php echo $this->translate('Make trash') ?>
                        </a>
                    <?php else : ?>
                        <?php echo $this->BlogPost()->getLinkToDealWithFavorite(
                            $this->mood['permalink'], \BlogUser\Model\FavoriteType::MOOD, isset($this->mood['isFavorite']), false) ?>

                        <?php if (isset($this->mood['hasUserReported'])) : ?>
                            <i class="icon icon-flag"></i><?php echo $this->translate('Already Reported') ?>
                        <?php else : ?>
                            <a href="" class='do-report-on-writing' rel='<?php echo $this->mood['mood_id'] ?>'><?php echo $this->translate('Make a complaint') ?></a>
                        <?php endif ?>

                        <?php if (isset($this->mood['isHidden'])) : ?>
                            <a href='<?php echo $this->url('unhide-my-blog-content', array('content_type'=>\NBlog\Model\WritingType::MOOD, 'permalink' => $this->mood['permalink'])) ?>'><?php echo $this->translate('Display again') ?></a>
                        <?php else : ?>
                            <a href='<?php echo $this->url('hide-my-blog-content', array('content_type'=>\NBlog\Model\WritingType::MOOD, 'permalink' => $this->mood['permalink'])) ?>'><?php echo $this->translate('Hide') ?></a>
                        <?php endif ?>
                    <?php endif ?>
                </div>

                <div class="post-summary">
                    <span><i class="icon icon-comment"></i><a href="#"><span class="commentCount"><?php echo $this->number()->convert($this->mood['total_comments']) ?></span></a></span>
                    <span><i class="icon-thumbs-up"></i><a href="#"><span class="likeCount"><?php echo $this->number()->convert($this->mood['total_favorited']) ?></span></a></span>
                </div>
            </div>

            <?php if ($this->mood['mood_status'] == \NBlog\Model\WritingStatus::PUBLISHED) : ?>
                <?php echo $this->partial('blog/partials/all-comments-view', array(
                    'commentOn' => $this->mood,
                    'comments' => $this->comments,
                    'creator' => $this->mood['mood_created_by'],
                    'userDetails' => $this->userDetails,
                    'commentFor' => \NBlog\Model\WritingType::MOOD,
                    'blockedBloggers' => $this->blockedBloggers,
                    'isBlocked' => isset($this->mood['isBlocked']),
                    'isWritingReported' => isset($this->mood['hasUserReported']),
                    'commentForm' => $this->commentForm,
                    'reportForm' => $this->reportForm
                )) ?>
            <?php endif ?>
        </div>
    </div>
</div>
