<?php if (empty($this->isAjax)) : ?>
<div class="row mySettings">
<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

    <?php echo $this->partial('blog-user/index/partials/settings_nav', array('is_active'=> 'account_setting')) ?>

</div><!-- End of right-column -->
<div class="cut-padding-left col-xs-12 col-sm-12 col-md-8 col-lg-8" id="setting-tab-content">
<?php endif ?>

<div id="accordion" class="panel-group">
<div class="panel panel-default">
    <div class="panel-heading bg1">
        <h4 class="panel-title">
            <a href="#collapseOne" data-parent="#accordion" data-toggle="collapse">
                <span class="title"><?php echo $this->translate('Name'); ?>:</span>
                <span class="value"><?php echo $this->userDetails['nickname']; ?></span>
            </a>
        </h4>
    </div>
    <div class="panel-collapse <?php echo ($this->settingType === 'name') ? 'in' : '' ?> collapse" id="collapseOne" style="height: auto;">
        <div class="panel-body">

            <?php $form = $this->formName->setAttribute('action', $this->url('change-account'))->prepare();
            echo $this->form()->openTag($form);
                $elementFirstName = $form->get('first_name'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="first_name"><?php echo $this->translate($elementFirstName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementFirstName) ?>
                        <?php echo $this->formElementerrors($elementFirstName); ?>
                    </div>
                </div>

                <?php $elementMiddleName = $form->get('middle_name'); ?>
                <div class="form-group">
                    <label class="col-md-3 col-lg-3 control-label" for="middle_name"><?php echo $this->translate($elementMiddleName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementMiddleName); ?>
                        <?php echo $this->formElementErrors($elementMiddleName); ?>
                    </div>
                </div>

                <?php $elementLastName = $form->get('last_name'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="last_name"><?php echo $this->translate($elementLastName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementLastName) ?>
                        <?php echo $this->formElementErrors($elementLastName); ?>
                    </div>
                </div>

                <?php $elementNickName = $form->get('nickname'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="nick_name"><?php echo $this->translate($elementNickName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementNickName) ?>
                        <?php echo $this->formElementErrors($elementNickName); ?>
                    </div>
                </div>

                <div class="form-group short-note">
                    <div class="col-md-offset-3 col-lg-offset-3 col-md-9 col-lg-9">
                        <?php echo $this->translate('To save these settings, please enter your nokkhotroblog password. '); ?>
                    </div>
                </div>

                <?php $elementPasswordName = $form->get('old_password'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="old_password"><?php echo $this->translate($elementPasswordName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementPasswordName) ?>
                        <?php echo $this->formElementErrors($elementPasswordName); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-lg-offset-2 col-md-10 col-lg-10">
                        <button class="btn btn-primary" name='change-type' value="name-change"
                                type="submit"><?php echo $this->translate('Save'); ?></button>
                        <button class="btn close-collapse" type="button"><?php echo $this->translate('Cancel'); ?></button>
                    </div>
                </div>

            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading bg1">
        <h4 class="panel-title">
            <a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="collapsed">
                <span class="title"> <?php echo $this->translate('Password'); ?>:</span>
                <span class="value">********</span>
                <span class="value pull-right"><?php echo $this->translate('Last update'); ?> <?php echo $this->DateTimeEnToBn()->timeSince($this->userDetails['modified']); ?></span>
            </a>
        </h4>
    </div>
    <div class="panel-collapse collapse <?php echo ($this->settingType === 'password') ? 'in' : '' ?>" id="collapseTwo">
        <div class="panel-body">

            <?php $form = $this->formPassword->setAttribute('action', $this->url('change-account'))->prepare();
            echo $this->form()->openTag($form) ?>

                <?php $elementOldPasswordName = $form->get('old_password'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="old_password"><?php echo $this->translate($elementOldPasswordName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementOldPasswordName) ?>
                        <?php echo $this->formElementErrors($elementOldPasswordName); ?>
                    </div>
                </div>

                <?php $elementPassword = $form->get('password'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="password"><?php echo $this->translate($elementPassword->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementPassword) ?>
                        <?php echo $this->formElementErrors($elementPassword); ?>
                    </div>
                </div>

                <?php $elementDoublePassword = $form->get('double_password'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="double_password"><?php echo $this->translate($elementDoublePassword->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementDoublePassword) ?>
                        <?php echo $this->formElementErrors($elementDoublePassword); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-lg-offset-2 col-md-10 col-lg-10">
                        <button class="btn btn-primary" name='change-type' value="password-change"
                                type="submit"><?php echo $this->translate('Save'); ?></button>
                        <button class="btn close-collapse" type="button"><?php echo $this->translate('Cancel'); ?></button>
                    </div>
                </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading bg1">
        <h4 class="panel-title">
            <a href="#collapseThree" data-parent="#accordion" data-toggle="collapse" class="collapsed">
                <span class="title"><?php echo $this->translate('Username'); ?>:</span>
                <span class="value"><?php echo $this->userDetails['username'] ?></span>
            </a>
        </h4>
    </div>
    <div class="panel-collapse collapse <?php echo ($this->settingType === 'username') ? 'in' : '' ?>" id="collapseThree">
        <div class="panel-body">

            <?php
            $form = $this->formUserName->setAttribute('action', $this->url('change-account'))->prepare();
            echo $this->form()->openTag($form); ?>
                <?php $elementUserName = $form->get('username'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="username"><?php echo $this->translate($elementUserName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementUserName) ?>
                        <?php echo $this->formElementErrors($elementUserName); ?>
                    </div>
                </div>

                <div class="form-group short-note">
                    <div class="col-md-offset-3 col-lg-offset-3 col-md-9 col-lg-9">
                        <?php echo $this->translate('To save these settings, please enter your nokkhotroblog password.') ?>d
                    </div>
                </div>

                <?php $elementPasswordName = $form->get('old_password'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="inputPassword"><?php echo $this->translate($elementPasswordName->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementPasswordName) ?>
                        <?php echo $this->formElementErrors($elementPasswordName); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-lg-offset-2 col-md-10 col-lg-10">
                        <button class="btn btn-primary" name='change-type' value="username-change"
                                type="submit"><?php echo $this->translate('Save'); ?></button>
                        <button class="btn close-collapse" type="button"><?php echo $this->translate('Cancel'); ?></button>
                    </div>
                </div>

            <?php echo $this->form()->closeTag() ?>

        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading bg1">
        <h4 class="panel-title">
            <a href="#collapseFour" data-parent="#accordion" data-toggle="collapse" class="collapsed">
                <span class="title"><?php echo $this->translate('Email'); ?>:</span>
                <span class="value"><?php echo $this->userDetails['email'] ?></span>
            </a>
        </h4>
    </div>
    <div class="panel-collapse collapse <?php echo ($this->settingType === 'email') ? 'in' : '' ?> " id="collapseFour">
        <div class="panel-body">

            <?php $form = $this->formEmail->setAttribute('action', $this->url('change-account'))->prepare();
            echo $this->form()->openTag($form) ?>

                <?php $elementEmail = $form->get('email') ?>
                <div class="form-group">
                    <label class="col-md-3 col-lg-3 control-label" for="email"><?php echo $this->translate($elementEmail->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementEmail) ?>
                        <?php echo $this->formElementErrors($elementEmail); ?>
                    </div>
                </div>

                <?php $elementNewEmail = $form->get('new_email'); ?>
                <div class="form-group error-occurred">
                    <label class="col-md-3 col-lg-3 control-label" for="inputPassword"><?php echo $this->translate($elementNewEmail->getLabel()); ?></label>
                    <div class="col-md-9 col-lg-9">
                        <?php echo $this->formInput($elementNewEmail) ?>
                        <?php echo $this->formElementErrors($elementNewEmail); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-lg-offset-2 col-md-10 col-lg-10">
                        <button class="btn btn-primary" name='change-type' value="email-change"
                                type="submit"><?php echo $this->translate('Save'); ?></button>
                        <button class="btn close-collapse" type="button"><?php echo $this->translate('Cancel'); ?></button>
                    </div>
                </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading bg1">
        <h4 class="panel-title">
            <a href="#collapseFive" data-parent="#accordion" data-toggle="collapse" class="collapsed">
                <span class="title"><?php echo $this->translate('Mobile'); ?>:</span>
                <span class="value"><?php echo empty($this->userDetails['mobile_no_for_sms']) ?
                        $this->translate('Not present') : $this->userDetails['mobile_no_for_sms'] . (empty($this->userDetails['is_sms_verified']) ? ' (' . $this->translate('Not verified yet') . ')' : '');?></span>
            </a>
        </h4>
    </div>

    <div class="panel-collapse collapse <?php echo ($this->settingType === 'mobile') ? 'in' : '' ?>" id="collapseFive" style="height: auto;">
        <div class="panel-body mobile-valid-area">

            <?php $form = $this->formPhoneVerifier->setAttributes(array(
                'style' => 'margin: 10px 0 0',
                'action' => $this->url('send-sms', array('id' => $this->sessionContainer()->getData('user_id')))
            ))->prepare();
            echo $this->form()->openTag($form); ?>

                <div class="short-note" id="count-down-box" style="display: none;">
                    <span style="font-size : 20px; color: #000"><?php echo $this->translate('You can send another sms after ') ?> </span><span id="count-down" style="color : red;"></span>
                </div>
                <div class="short-note">
                    <?php echo $this->translate('Please enter your  mobile number.') ?>
                </div>
                <div class="form-group col-md-5 col-lg-5 error-occurred">
                    <?php $countryCode = $form->get('country_code');
                    if (!empty($this->isVerificationOpen)) {
                        $countryCode->setValue($this->userDetails['country_code']);
                        $countryCode->setAttribute('disabled','disabled');
                    }
                    echo $this->formSelect($countryCode); ?>
                    <span class='field-error'><?php echo $this->formElementErrors($countryCode) ?></span>
                </div>
                <div class="form-group col-md-4 col-lg-4 error-occurred">
                    <?php $phone = $form->get('phone');
                    if (!empty($this->isVerificationOpen)) {
                        $phone->setValue($this->userDetails['mobile_no_for_sms']);
                        $phone->setAttribute('readonly',true);
                    }
                    echo $this->formInput($phone); ?>
                    <span class='field-error'><?php echo $this->formElementErrors($phone) ?></span>
                </div>
            <?php
            $form->get('verify')->setAttribute('value',(!empty($this->isVerificationOpen))?'resend':'save');
            echo $this->formSubmit($form->get('verify')) ?>
            <a class="change-mobile-no" style="<?php echo (!empty($this->isVerificationOpen))? 'display:block;' : 'display:none;'?>" href="javascript:void(0);"><?php echo $this->translate('Change number.') ?> </a>
            <div class="account-pre-loader-img"></div>
            <div id='error_of_phone'></div>

            <?php echo $this->form()->closeTag(); ?>
            <br /><br />

            <div id='verification-block' style="<?php echo (!empty($this->isVerificationOpen))? 'display:block;' : 'display:none;'?>">

                <div class="short-note">
                    <?php echo $this->translate('Please Write Your Verification Code.') ?>
                </div>
                <?php $form = $this->formCodeVerifier->setAttributes(array(
                    'style' => 'margin: 0',
                    'action' => $this->url('verify-code', array('id' => $this->sessionContainer()->getData('user_id')))
                ))->prepare();
                echo $this->form()->openTag($form); ?>

                <div class="form-group col-md-6 col-lg-6 error-occurred">
                    <?php $smsCode = $form->get('sms_code') ?>
                    <?php echo $this->formInput($smsCode) ?>
                    <?php echo $this->formElementErrors($smsCode) ?>
                </div>
                <?php echo $this->formSubmit($form->get('verify')) ?>
                <div class="account-pre-loader-img"></div>
                <div id='error_of_code'></div>
                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>

</div>

</div>
<?php if (empty($this->isAjax)) : ?>
</div>
</div>
<?php endif ?>

<script type='text/javascript'>

    function update(sec){
        $('#setting-tab-content').find('#count-down').html(nbUtility.convertReadableTime(sec));
    }
    var totalTime = '<?php echo $this->smsExpireTime ?>';
    var myCounter = new Countdown({
        seconds:totalTime,
        boxTimer:$('#count-down'),
        timerBoxHolder:$('#count-down-box'),
        onUpdateStatus: update,
        onCounterEnd: function() {

        }
    });
    myCounter.start();

    $(function() {
        var $settingTabDom = $('#setting-tab-content');
        $settingTabDom.find('#phone-verify').validate({
            groups: {
                completePhone: 'country_code phone'
            },
            rules: {
                'country_code': { required: true },
                'phone': { required: true }
            },
            messages: {
                'country_code': { required: '<?php echo $this->translate('Please select your country code.') ?>' },
                'phone': { required: '<?php echo $this->translate('Please enter your phone number.') ?>' }
            },
            errorPlacement: function ($error, $element) {
                if ($element.attr('name') == 'country_code' || $element.attr('name') == 'phone') {
                    $('div[id="error_of_phone"]').append($error);
                } else {
                    $error.insertAfter($element);
                }
            },
            submitHandler: function(form) {
                mySiteAjax({
                    url: $(form).attr('action'),
                    data: $(form).serialize(),
                    success: function(response) {
                        nbUtility.ajaxErrorHandling(response, function() {
                            $('#verification-block').slideDown();
                        }, {
                            errorCallback: function(response) {
                                var msg = '';
                                if (response.data == 'max-time-send') {
                                    msg = '<?php echo $this->translate('You can  send sms after 2 hr.') ?>';
                                    $("#verification-block").slideDown();
                                } else if (response.data == 'sms-not-sent') {
                                    msg = '<?php echo $this->translate('Sms has not been sent.') ?>';
                                } else if (response.data == 'blocked') {
                                    msg = '<?php echo $this->translate('You can  send sms after :') ?> '+nbUtility.convertReadableTime(response.remainTime);
                                } else if(response.data == 'already-used'){
                                    msg = '<?php echo $this->translate('This number already used') ?>';
                                }else {
                                    msg = '<?php echo $this->translate('Something went wrong. Please try again.') ?>';
                                }
                                alertify.success(msg);
                            }
                        });
                    }
                });
            }
        });

        $settingTabDom.find('#code-verify').validate({
            rules: {
                'sms_code': { required: true }
            },
            messages: {
                'sms_code': { required: '<?php echo $this->translate('Please enter the verification code.') ?>' }
            },
            errorPlacement: function ($error, $element) {
                if ($element.attr('name') == 'sms_code') {
                    $('div[id="error_of_code"]').append($error);
                } else {
                    $error.insertAfter($element);
                }
            },
            submitHandler: function(form) {
                mySiteAjax({
                    url: $(form).attr('action'),
                    data: $(form).serialize(),
                    success: function(response) {
                        nbUtility.ajaxErrorHandling(response, function() {
                            $settingTabDom.find('#verification-block').slideUp(600,function(){
                                alertify.alert('<?php echo $this->translate('Code has been verified.') ?>');
                            });
                        }, {
                            errorCallback: function(response) {
                                var msg = '';
                                if (response.data == 'code-not-valid') {
                                    msg = '<?php echo $this->translate('Code has not been verified.') ?>';
                                } else {
                                    msg = '<?php echo $this->translate('Something went wrong. Please try again.') ?>';
                                }
                                alertify.success(msg);
                                $settingTabDom.find('#sms_code').val('');
                            }
                        });
                    }
                });
            }
        });

        $settingTabDom.on('click', 'a.change-mobile-no', function(){
            $settingTabDom.find('#country_code').removeAttr('disabled');
            $settingTabDom.find('#phone').removeAttr('readonly');
        });

        $settingTabDom.find("#account-name-setting").validate({
            rules: {
                'first_name': { required: true },
                'last_name': { required: true },
                'nickname': { required: true },
                'old_password': { required: true }
            },messages: {
                'first_name': { required: 'First name is Required' },
                'last_name': { required: 'Last name is Required' },
                'nickname': { required: 'Display name  is Required' },
                'old_password': { required: 'Password is Required' }
            },
            submitHandler: function (form) {
                mySiteAjax({
                    url: $(form).attr('action'),
                    data: $(form).serialize(),
                    success: function(response) {
                        dealWithServerResponse(response);
                    }
                });
            }
        });

        $settingTabDom.find("#user-password-form").validate({
            rules: {
                'old_password': { required: true },
                'password': { required: true , minlength: 6},
                'double_password': { required: true, equalTo: "#password" , minlength: 6}
            },messages: {
                'old_password': { required: 'Old Password Required' },
                'password': { required: 'New password Required' ,  minlength:'Minimun 6 characters'},
                'double_password': { required: 'Confirm Password Required' , equalTo: 'Not Equal', minlength:'Minimun 6 characters'}
            },
            submitHandler: function (form) {
                mySiteAjax({
                    url: $(form).attr('action'),
                    data: $(form).serialize(),
                    success: function(response) {
                        dealWithServerResponse(response);
                    }
                });
            }
        });

        $.validator.addMethod(
            'alphaNumericDot',
            function(value) {
                var regEx = new RegExp('^([a-z0-9\.])+$', 'gi');
                return regEx.test(value);
            },
            nbUtility.translate('Please enter a string which contains alphabetic, digits and dot characters.')
        );

        $.validator.addMethod(
            'notReservedWord',
            function(value) {
                var reservedWords = ['me'];
                return $.inArray(value, reservedWords) < 0;
            },
            nbUtility.translate('Please enter any other string except the reserved words: me.')
        );

        $settingTabDom.find("#account-username-setting").validate({
            rules: {
                'old_password': { required: true },
                'username': {
                    required: true,
                    alphaNumericDot: true,
                    notReservedWord: true,
                    remote: {
                        url: '<?php echo $this->url('check-username-unique') ?>',
                        type: 'POST'
                    }
                }
            },messages: {
                'old_password': { required: 'Password Required' },
                'username': {
                    required: 'Username Required',
                    remote: '<?php echo $this->translate('Username given is already used.') ?>'
                }
            },
            submitHandler: function (form) {
                mySiteAjax({
                    url: $(form).attr('action'),
                    data: $(form).serialize(),
                    success: function(response) {
                        dealWithServerResponse(response);
                    }
                });
            }
        });

        $settingTabDom.find("#account-email-change").validate({
            rules: {
                'new_email': { required: true ,email: true}
            },messages: {
                'new_email': { required: 'Email Required'}
            },
            submitHandler: function (form) {
                mySiteAjax({
                    url: $(form).attr('action'),
                    data: $(form).serialize(),
                    success: function(response) {
                        dealWithServerResponse(response);
                    }
                });
            }
        });

        function dealWithServerResponse(response) {
            if (response.status == 'success') {
                alertify.success(response.data);
                $('#setting-tab-content').html(response.html);
            } else {
                alertify.alert(response.data);
            }
        }
    });

</script>