<table class="vote-photo-gallery">
    <caption>
        <div class="box-header">
            <h1>সৃজনশীল ব্লগিং প্রতিযোগিতা ২০১৪</h1>
        </div>
    </caption>

    <tbody>
    <tr>
        <td>
            <a class="each-photo-gallery-image" href="/img/vote-gallery/orginal/vote-img1.jpg"><img class="lazy" src="/img/vote-gallery/resize/vote-img1.jpg" data-original=""></a><br />
            <span> image 1</span>
        </td>
        <td>
            <a class="each-photo-gallery-image" href="/img/vote-gallery/orginal/vote-img1.jpg"><img class="lazy" src="/img/vote-gallery/resize/vote-img1.jpg" data-original=""></a><br />
            <span> image 1</span>
        </td>
    </tr>
    <tr>
        <td>
            <a class="each-photo-gallery-image" href="/img/vote-gallery/orginal/vote-img1.jpg"><img class="lazy" src="/img/vote-gallery/resize/vote-img1.jpg" data-original=""></a><br />
            <span> image 1</span>
        </td>
        <td>
            <a class="each-photo-gallery-image" href="/img/vote-gallery/orginal/vote-img1.jpg"><img class="lazy" src="/img/vote-gallery/resize/vote-img1.jpg" data-original=""></a><br />
            <span> image 1</span>
        </td>
    </tr>
    <tr>
        <td>
            <a class="each-photo-gallery-image" href="/img/vote-gallery/orginal/vote-img1.jpg"><img class="lazy" src="/img/vote-gallery/resize/vote-img1.jpg" data-original=""></a><br />
            <span> image 1</span>
        </td>
        <td>
            <a class="each-photo-gallery-image" href="/img/vote-gallery/orginal/vote-img1.jpg"><img class="lazy" src="/img/vote-gallery/resize/vote-img1.jpg" data-original=""></a><br />
            <span> image 1</span>
        </td>
    </tr>
    </tbody>
</table>
