<h3>
    <?php echo $this->translate('My favorite posts') ?>
    (<?php echo $this->Number()->convert($this->countFavoritePosts) ?><?php echo $this->translate('#') ?>)
</h3>

<form action="<?php echo $this->url('cancel-favorite-bulky') ?>" method="POST">
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th class="optional"></th>
            <th><?php echo $this->translate('Blog Title') ?></th>
            <th class="optional"><?php echo $this->translate('Post Information') ?></th>
            <th class="optional">&nbsp;</th>
        </tr>
        </thead>

        <tbody>
        <?php if (empty($this->favoritePosts)) : ?>

        <tr>
            <td colspan="4"><p class="no-record-found"><?php echo $this->translate('No post has been favorited.') ?></p></td>
        </tr>

        <?php else : foreach ($this->favoritePosts AS $post) : ?>

        <tr>
            <td class="optional"><input type="checkbox" name='postIds[]' value="<?php echo $post['post_id'] ?>" class="post_ids" /></td>
            <td><a href="<?php echo $this->url('view-my-post', array('permalink' => $post['permalink'])) ?>"><?php echo $this->NBEscapeHtml($post['title']) ?></a></td>
            <td>
            <span class="postmeta">
                <?php echo $this->translate('Writer') ?>: <?php echo $this->Profile()->getDisplayName($post) ?> <br />
                <?php echo $this->translate('Published') ?>: <?php echo $this->DateTimeEnToBn()->ShowDateOnly($post['published']) ?> <br />
                <?php echo $this->translate('Total Posts') ?>: <?php echo $this->Number()->convert($post['total_comments']) ?>টি <br />
                <?php echo $this->translate('Total Visited') ?>: <?php echo $this->Number()->convert($post['total_viewed']) ?> বার <br />
                <?php echo $this->translate('Total Favorite-doer') ?>: <?php echo $this->Number()->convert($post['total_favorited']) ?> জ্ন
            </span>
            </td>
            <td><input type="button" value="অপ্রিয় করুন" class="btn btn-primary do-only-one" /></td>
        </tr>

        <?php endforeach; endif ?>
        </tbody>
    </table>

    <?php if (!empty($this->favoritePosts)) : ?>

    <div class="pagination pagination-centered">
        <div class="form-inline pull-left">
            <input type="submit" value="একসাথে অপ্রিয় করুন" class="btn btn-primary" />
            <input type="hidden" name='urlFrom' value="<?php echo $_SERVER['REQUEST_URI'] ?>" />
            <input type="hidden" name='type' value="<?php echo \BlogUser\Model\FavoriteType::POST ?>" />
            <?php echo $this->paginator()->slide($this->paginator, array_merge($this->paginatorOptions, array('linksOnly' => true, 'class' => 'pull-right'))) ?>
        </div>
    </div>

    <?php endif ?>

</form>

<script type='text/javascript'>
    (function($) {
        $('#select-all').on('click', function() {
            $(this).parent().parent().parent()
                    .find("input[type='checkbox']").attr('checked', $(this).is(':checked'));
        });

        $('.post_ids').click(function() {
            $('#select-all').attr('checked', $(this).is(':checked') &&
                    ! ($(this).parent().parent().siblings("tr").children("tr > td > input[type='checkbox']").not(':checked').length));
        });

        $('.do-only-one').click(function() {
            $(this).parent().parent().find("td > input[type='checkbox']").attr('checked', true);
            $(this).parents('form:first').submit();
        });
    })(jQuery);

</script>