<?php if (!empty($this->categories_for_form)) : ?>
    <?php $count = 0; $editText = (!empty($this->isEdit)) ? 'edit-' : '' ?>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <?php foreach ($this->categories_for_form AS $category) : ?>
        <div class="group bg1 bd bds3">
            <div class="radioBox" style="display: <?php echo (empty($editText) ? 'none' : 'inline-block') ?>">
                <div class="checkbox">
                    <label>
                        <input data-onbeforeunload="1" type="checkbox" name="category_id[]" value="<?php echo $category['category_id']?>"
                            <?php echo (in_array($category['category_id'], $this->selectedCategories) ? 'checked="checked"' : '') ?>
                            />
                        <i class="icon-"></i><?php echo $category['name'] ?>
                    </label>
                </div>
            </div>
            <span style="display: <?php echo (empty($editText) ? 'block' : 'none') ?>"><?php echo $category['name'] ?></span>
            <i    style="display: <?php echo (empty($editText) ? 'none' : 'inline') ?>" class="icon-minus" id="plus-minus"></i>

            <?php if (!empty($category['children'])) : ?>
            <div class="child-group" style="display: <?php echo (empty($editText) ? 'none' : 'block') ?>">
                <div class="radioBox">
                    <?php foreach ($category['children'] AS $subCategory) : ?>
                        <div class="checkbox">
                            <label>
                                <input data-onbeforeunload="1" type="checkbox" name="category_id[]" value="<?php echo $subCategory['category_id'] ?>"
                                    <?php echo (in_array($subCategory['category_id'], $this->selectedCategories) ? 'checked="checked"' : '') ?> />
                                <i class="icon-"></i><?php echo $subCategory['name'] ?>
                            </label>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?php endif ?>
        </div>
        <?php if (!(++$count % 3)) : ?>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <?php endif ?>
    <?php endforeach ?>
    </div>
<?php endif ?>
