<div id="comment-edit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <input type="hidden" id="comment-edit-link" name="comment-edit-link" value="<?php echo $this->url('edit-comment', array('id'=>'commentId')) ?>">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><?php echo $this->translate('Comment Edit box');?></h3>
    </div>
    <div class="modal-body">

    </div>
</div>