<div class="row-fluid">
    <div class="mail_action_header">
          <span class="header_action">
           <span data-title=" পিছনে যান " class="inbox_back" data-original-title="" title=""><a href="inbox_message_ajax.html"><img src="<?php echo $this->basePath('img/user/back_button.png')?>" class="mail_back">
               </a> </span>
          <span data-title="নির্বাচন করুন " class="mail_select" data-original-title="" title=""><a href="#"><i class="icon-ok-circle"></i> <b class="caret pull-rightp"></b>
              </a> </span>
          <span data-title="রিফ্রেশ করুন  " class="mail_refresh" data-original-title="" title=""><a href="#"><i class="icon-refresh"></i></a> </span>
          <span data-title="আরও " class="mail_more" data-original-title="" title=""><a href="#"><i class="icon-play-circle"></i></a> </span>
      </span>
    <span class="header_delete">
          <span data-title=" সংরক্ষণাগার" class="mail_archive" data-original-title="" title="">
              <a id="draft_email" href="#"><i class="icon-circle-arrow-down"></i>
              </a> </span>
          <span data-title=" স্প্যাম রিপোর্ট " class="mail_spam_simbol" data-original-title="" title=""><a href="#"><i class="icon-exclamation-sign"></i>
              </a> </span>
          <span data-title="মুছে ফেলুন " class="mail_delete_simbol"  data-original-title="" title="">
              <a href="#" id="email_delete"><i class="icon-trash"></i>
              </a> </span>
      </span>
      <span class="header_move">
          <span data-title="
               স্থানান্তর  করুন    " class="mail_move_to" data-original-title="" title=""><a href="#"><i class="icon-folder-close"></i>
                  <b class="caret"></b>
              </a>
          </span>
          <span data-title="চিরকুট" class="mail_spam_simbol" data-original-title="" title=""><a href="#"><i class="icon-tags"></i>
                  <b class="caret"></b>
              </a>
          </span>
      </span>
    </div>
</div>