<?php $privacyFieldset = $this->form->get('privacy') ?>
<div id="professional_info_privacy_table">
    <div class="form-group">
        <label class="col-md-3 col-lg-3 control-label" for="profession"><?php echo $this->translate('Profession') ?> :</label>
        <div class="col-md-9 col-lg-9">
            <?php $element = $this->professionalInfoFieldset->get('profession'); ?>:
            <?php echo $this->formElement($element) ?>
            <label class="control-label for-display display-show"> <?php echo empty($this->userDetail['profession']) ? $this->translate('Undefined') : $this->professions[$this->userDetail['profession']] ?></label>
            <?php echo $this->partial('blog-user/index/partials/privacy_dropdown', array(
                'privacyElement' => $privacyFieldset->get(\NBlog\Model\Setting::PROFESSION_PRIVACY),
                'privacyOptions' => $this->privacyOptions
            )) ?>
            <label class="error" generated="true" for="profession"><?php echo $this->formElementErrors($element); ?></label>
        </div>
    </div>

    <!-- <div class="form-group error-occurred"> -->
    <div class="form-group">
        <label class="col-md-3 col-lg-3 control-label" for="workplace"><?php echo $this->translate('Institute') ?> :</label>
        <div class="col-md-9 col-lg-9">
            <?php $element = $this->professionalInfoFieldset->get('workplace'); ?>:
            <?php echo $this->formElement($element) ?>
            <label class="control-label for-display display-show"> <?php echo $this->Text()->getNotNullText($this->userDetail['workplace']) ?></label>
            <?php echo $this->partial('blog-user/index/partials/privacy_dropdown', array(
                'privacyElement' => $privacyFieldset->get(\NBlog\Model\Setting::INSTITUTE_PRIVACY),
                'privacyOptions' => $this->privacyOptions
            )) ?>
            <label class="error" generated="true" for="workplace"> <?php echo $this->formElementErrors($element); ?></label>
        </div>
    </div>

<!-- <div class="form-group error-occurred"> -->
    <div class="form-group">
        <label class="col-md-3 col-lg-3 control-label" for="designation"><?php echo $this->translate('Designation') ?> :</label>
        <div class="col-md-9 col-lg-9">
            <?php $element = $this->professionalInfoFieldset->get('designation'); ?>
            <?php echo $this->formElement($element) ?>
            <label class="control-label for-display display-show"> <?php echo $this->Text()->getNotNullText($this->userDetail['designation']) ?></label>
            <?php echo $this->partial('blog-user/index/partials/privacy_dropdown', array(
                'privacyElement' => $privacyFieldset->get(\NBlog\Model\Setting::DESIGNATION_PRIVACY),
                'privacyOptions' => $this->privacyOptions
            )) ?>
            <label class="error" generated="true" for="designation"><?php echo $this->formElementErrors($element); ?></label>
        </div>
    </div>

    <div id="go-to-action" class="form-group display-hide">
        <div class="col-md-offset-2 col-lg-offset-2 col-md-10 col-lg-10">
            <?php echo $this->formSubmit($this->form->get('submit')->setAttributes(array(
                'name' => $this->professionalInfoFieldset->getName().'_submit', 'onclick' => 'cancelDisabledField();'))) ?>
            <?php echo $this->formElement($this->form->get('cancel')); ?>
        </div>
    </div>

</div>