<div class="comments-group">
    <div class="comments pht">
        <div class="post-hit-count">
            <div class="dropdown">
                <a data-toggle="dropdown" id="dropdownMenu1" class="dropdown-toggle">
                    <i class="icon-angle-down"></i>
                </a>
                <ul role="menu" class="dropdown-menu pull-right">

                    <?php if ($this->eachCommentsData['user_id'] == $this->sessionContainer()->getData('user_id')) : ?>
                    <li>
                        <a href="javascript:void(0)" rel="comment" class="delete-comment" id="delete_comment_id_<?php echo $this->eachCommentsData['comment_id']?>">
                            <i class="icon-eraser"></i><span></span> <?php echo $this->translate('Delete This') ?>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0)" rel="comment" class="get-edit-comment" id="edit_comment_id_<?php echo $this->eachCommentsData['comment_id']?>">
                            <i class="icon-pencil"></i> <?php echo $this->translate('Edit This') ?>
                        </a>
                    </li>
                    <?php else : ?>
                    <li>
                        <a class='hide-it' rel="<?php echo $this->eachCommentsData['comment_id'] ?>" data-reported-on="<?php echo \NBlog\Model\WritingType::COMMENT ?>">
                            <i class='icon-eye-close'></i> <?php echo $this->translate('Hide') ?>
                        </a>
                    </li>
                    <?php if (!isset($this->eachCommentsData['hasUserReported'])) : ?>
                    <li>
                        <a class='complain-it' rel="<?php echo $this->eachCommentsData['comment_id'] ?>" data-reported-on="<?php echo \NBlog\Model\WritingType::COMMENT ?>">
                            <i class='icon-shield'></i> <?php echo $this->translate('Make a complaint') ?>
                        </a>
                    </li>
                    <?php endif ?>
                    <?php endif;?>
                </ul>
            </div>

        </div>
        <img src="<?php echo $this->Profile()->getImage($this->eachCommentsData) ?>" class="commentator"/>
        <div class="comments-bubble">
            <div class="comments-by">
                <a href="<?php echo $this->url('public-profile', array('username' => $this->eachCommentsData['username'])) ?>">
                    <?php echo $this->Post()->getNewUserInfoLinkWithPopUpPost($this->eachCommentsData, 'right', $this->professions) ?>
                </a>
                <?php echo $this->translate('Has been commented') ?>
                <?php echo $this->DateTimeEnToBn()->timeSince($this->eachCommentsData['comment_created']) ?>
            </div>
            <div class="comments-body">
                <?php  echo $this->NBEscapeHtml($this->eachCommentsData['comments'],true); ?>
                <?php if(!empty($this->eachCommentsData['replies'])): ?>
                    <a href="" class="full-comments-view">
                        মন্তব্যে <?php echo  $this->Number()->convert(count($this->eachCommentsData['replies']))?>  টি উত্তর আছে ..
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <div class="complain-here"></div>
    </div>

    <?php if (!empty($this->eachCommentsData['replies'])) : foreach ($this->eachCommentsData['replies'] AS $eachReplyData) : ?>
        <?php echo $this->partial('blog-user/index/partials/user_wall_single_reply',array(
            'eachReplyData' => $eachReplyData,
            'professions'   => $this->professions
        ));?>
    <?php endforeach; endif ?>

    <?php echo $this->partial('blog-user/index/partials/user_wall_single_comment_form',array(
        'currentUser'       => $this->sessionContainer()->getData('user_id'),
        'commentOn'         => $this->commentOn,
        'commentFor'        => $this->commentFor,
        'commentForm'       => $this->commentForm,
        'commentIn'         => $this->eachCommentsData['comment_id'],
        'formForReply'      => true
    )) ?>
</div>
