<div class="comments ans pht">
<div class="post-hit-count">
    <div class="dropdown">
        <a data-toggle="dropdown" id="dropdownMenu1" class="dropdown-toggle">
            <i class="icon-angle-down"></i>
        </a>
        <ul role="menu" class="dropdown-menu pull-right">
            <?php if($this->eachReplyData['user_id'] == $this->sessionContainer()->getData('user_id')):?>
                <li>
                    <a href="javascript:void(0)" rel="reply" class="delete-comment" id="delete_comment_id_<?php echo $this->eachReplyData['comment_id']?>">
                        <i class="icon-eraser"></i><span></span> <?php echo $this->translate('Delete This') ?>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)" rel="reply" class="get-edit-reply" id="edit_comment_id_<?php echo $this->eachReplyData['comment_id']?>">
                        <i class="icon-pencil"></i> <?php echo $this->translate('Edit This') ?>
                    </a>
                </li>
            <?php else : ?>
                <li>
                    <a class='hide-it' rel="<?php echo $this->eachReplyData['comment_id'] ?>" data-reported-on="<?php echo \NBlog\Model\WritingType::COMMENT ?>">
                        <i class='icon-eye-close'></i> <?php echo $this->translate('Hide') ?>
                    </a>
                </li>
                <?php if (!isset($this->eachReplyData['hasUserReported'])) : ?>
                <li>
                    <a class='complain-it' rel="<?php echo $this->eachReplyData['comment_id'] ?>" data-reported-on="<?php echo \NBlog\Model\WritingType::COMMENT ?>">
                        <i class='icon-shield'></i> <?php echo $this->translate('Make a complaint') ?>
                    </a>
                </li>
            <?php endif ?>
            <?php endif;?>
        </ul>
    </div>

</div>
<img src="<?php echo $this->Profile()->getImage($this->eachReplyData) ?>" class="commentator"/>
<div class="comments-bubble">
    <div class="comments-by">
        <a href="<?php echo $this->url('public-profile', array('username' => $this->eachReplyData['username'])) ?>">
            <?php echo $this->Post()->getNewUserInfoLinkWithPopUpPost($this->eachReplyData, 'right', $this->professions) ?>
        </a>
        <?php echo $this->translate('Has been commented') ?>
        <?php echo $this->DateTimeEnToBn()->timeSince($this->eachReplyData['comment_created']) ?>
    </div>
    <div class="comments-body">
        <?php  echo $this->NBEscapeHtml($this->eachReplyData['comments'],true); ?>
    </div>
</div>
<div class="complain-here"></div>
</div>