
<div class="box span24">
    <div class="box-header">
        <h2><?php echo $this->translate('Blog Series') ?><i class="icon icon-arrow-up icon-white"></i></h2>


    </div>
    <div class="box-content">
        <ul class="nav nav-list" style="list-style: none; padding: 0px;">
            <li><a href="" class="postlink"><i class="icon icon-adjust"></i><?php echo $this->translate('Police Beatings') ?></a></li>
            <li><a href="" class="postlink"><i class="icon icon-adjust"></i><?php echo $this->translate('Non-violent Politics') ?></a></li>
            <li><a href="" class="postlink"><i class="icon icon-adjust"></i><?php echo $this->translate('Muhit Resignation') ?></a></li>
            <li><a href="" class="postlink"><i class="icon icon-adjust"></i><?php echo $this->translate('Victory of Jamayat') ?></a></li>
            <li><a href="" class="postlink"><i class="icon icon-adjust"></i><?php echo $this->translate('Bangladeshi War') ?></a></li>
            <li><a href="" class="postlink"><i class="icon icon-adjust"></i><?php echo $this->translate('Next Election') ?></a></li>
        </ul>
    </div>
</div>