
<div class="box span24">
    <div class="box-header">
        <h2><?php echo $this->translate('Featured Category') ?><i class="icon icon-arrow-up icon-white"></i></h2>


    </div>

    <div class="box-content">
        <ul class="nav nav-list" style="list-style: none; padding: 0">
            <li><a href="<?php echo $this->url('category', array('permalink' => $this->translate('Contemporary'))) ?>" class="postlink"><?php echo $this->translate('Contemporary') ?></a></li>
            <li><a href="<?php echo $this->url('category', array('permalink' => $this->translate('Poetry'))) ?>" class="postlink"><?php echo $this->translate('Contemporary') ?></a></li>
            <li><a href="<?php echo $this->url('category', array('permalink' => $this->translate('Information-Technology'))) ?>" class="postlink"><?php echo $this->translate('Information-Technology') ?></a></li>
            <li><a href="<?php echo $this->url('category', array('permalink' => $this->translate('Sport'))) ?>" class="postlink"><?php echo $this->translate('Sport') ?></a></li>
            <li><a href="<?php echo $this->url('category', array('permalink' => $this->translate('Politics'))) ?>" class="postlink"><?php echo $this->translate('Politics') ?></a></li>
        </ul>
    </div>
</div>