<div class="content-wrap col-xs-12 col-sm-12 col-md-12 col-lg-12">
<div class="row">
    <div class="main-container col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <?php echo $this->partial('blog/pages/static_page_links', array('pageNav' => $this->pageNav)) ?>

            <div class="mid-column col-xs-12 col-sm-5 col-md-9 col-lg-9">
                <div class="tile col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="tile-header"><?php echo $this->translate('Frequently Asked Question') ?></div>
                    <div class="tile-body">
                        <div class="row">
                            <div class="tile-container FAQ col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="panel-group" id="accordion">
                                    <?php foreach($this->categoryList AS $category) : ?>
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse_<?php echo $category['category_id']?>">
                                                    <?php echo $category['name'] ?>
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapse_<?php echo $category['category_id'] ?>"
                                             class="panel-collapse collapse<?php echo empty($panelCollapse) ? ' in' : '' ?>">
                                            <div class="panel-body">
                                                <?php if (!empty($category['questions'])) : ?>
                                                <ul>
                                                    <?php foreach($category['questions'] AS $list): ?>
                                                    <li><span class="qus"><?php echo $this->translate('Question') ?> : </span><?php echo $list['question'] ?></li>
                                                    <li><span class="ans"><?php echo $this->translate('Answer') ?> :</span><?php echo $list['answer'] ?></li>
                                                    <?php endforeach ?>
                                                </ul>
                                                <?php endif ?>
                                            </div>
                                        </div>
                                    </div>
                                    <?php $panelCollapse = true; endforeach ?>
                                </div>
                            </div>
                        </div>
                    </div><!--  End of tile-body  -->
                </div><!--    End of tile    -->
            </div><!--  End of left-column  -->
        </div>
    </div><!--  End of main-container  -->
</div>
</div>