
<?php $form = $this->commentForm->setAttribute('action', $this->url('save-comment', array(
    'permalink' => $this->writingPermalink,
    'username' => $this->sessionContainer()->getData('username'))
))->prepare() ?>
    <div class="comments-area col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php  echo $this->form()->openTag($form) ?>
        <?php $element = $form->get('comment') ?>
        <?php echo $this->formTextarea($element) ?>
        <?php echo $this->formElementErrors($element) ?>
        <div class="pull-right">
            <?php $submit = $form->get('submit')->setValue('Write Comment');
            echo $this->formSubmit($submit->setAttribute('class', $submit->getAttribute('class').($this->sessionContainer()->getData('isSmsVerified') ? '' : ' verify-sms'))); ?>
            <a href="javascript:void(0)" class="cancel-commenting btn btn-small">
                <?php echo $this->translate('Cancel') ?>
            </a>
            <?php echo $this->formHidden($form->get('comment_for')->setValue($this->commentFor)) ?>
        </div>
    </div>
<?php echo $this->form()->closeTag() ?>
