
<?php $form = $this->reportForm->setAttributes(array(
    'action' => $this->url('report'),
    'id' => 'report-form' . ($this->formId ? "-{$this->formId}" : '')
))->prepare();
echo $this->form()->openTag($form) ?>
<div class="control-group">
    <label><?php echo $this->translate('Please inform us about your report: ') ?></label>
    <div class="controls">
        <div class="row-fluid">
            <?php $reportMessages = $form->get('message_id')->getValueOptions() ?>
            <?php $count = 0; foreach ((array)$reportMessages AS $key => $message) : ++$count ?>
            <label class="radio inline">
                <input type="radio" name="message_id" value="<?php echo $key ?>">
                <?php echo $message ?>
            </label>
            <?php if (!($count % 5)) : ?>
        </div>
        <div class="row-fluid">
            <?php endif ?>
            <?php endforeach ?>
        </div>
    </div>
</div>

<span class="pull-right">
    <?php $submit = $form->get('submit');
    echo $this->formSubmit($submit->setAttribute('class', $submit->getAttribute('class').' btn-small'.($this->sessionContainer()->getData('isSmsVerified') ? '' : ' verify-sms'))); ?>
    <a class="cancel-reporting btn btn-small"><?php echo $this->translate('Cancel') ?></a>
    <?php echo $this->formHidden($form->get('id_of_reported_on')->setValue($this->idOfReportedOn)) ?>
    <?php echo $this->formHidden($form->get('reported_on')->setValue($this->reportedOn)) ?>
</span>
<?php echo $this->form()->closeTag(); ?>
