<?php $currentUser = $this->sessionContainer()->getData('user_id') ?>
<?php $currentUsername = $this->sessionContainer()->getData('username') ?>
<div class="single-reply span24">
    <a href="#"><img src="<?php echo $this->Profile()->getImage($this->reply) ?>"></a>

    <div class="commenter-detail">
        <a href="<?php echo $this->url('public-profile', array('username' => $this->reply['username'])) ?>">
            <?php echo $this->Post()->getUserInfoLinkWithPopUpPost($this->reply, 'right', $this->professions) ?></a>
        <?php echo $this->translate('Has been commented') ?>
        <span data-toggle="tooltip" title="<?php echo $this->DateTimeEnToBn()->ShowDate($this->reply['comment_created']) ?>"><?php echo $this->DateTimeEnToBn()->timeSince($this->reply['comment_created']) ?></span>
        <span class="pull-right">
            <i class="icon-thumbs-up"></i>
            <span class="likeCount"><?php echo $this->number()->convert($this->reply['total_comment_favorited']) ?></span>
        </span>
    </div>
    <div class="reply-detail"><?php echo $this->NBEscapeHtml($this->reply['details'], true) ?></div>
    <div class="reply-actions">
        <div class="pull-right">
            <?php if ($currentUsername) : ?>
                <?php if (in_array($currentUser, array($this->creator, $this->comment['comment_created_by'], $this->reply['comment_created_by']))) : ?>
                    <i class="icon icon-trash"></i>
                    <a href="<?php echo $this->url('delete-comment-from-post', array('username'=>'me', 'id'=>$this->reply['comment_id'])) ?>"
                       class="delete-comment" rel='<?php echo $this->reply['username'] ?>' data-askForBlock = '<?php echo ($currentUser != $this->reply['comment_created_by']) ?>'
                       data-permalink='<?php echo $this->writingPermalink ?>'><?php echo $this->translate('Delete This') ?></a>
                <?php endif ?>

                <?php if ($currentUser == $this->reply['comment_created_by']) : ?>
                    <a id="comment_id_<?php echo $this->reply['comment_id'] ?>" class="edit-comment" rel="reply" href='javascript:void(0)'>
                        <i class="icon-pencil"></i><?php echo $this->translate('Edit This') ?>
                    </a>
                <?php else : ?>
                    <?php echo $this->BlogPost()->getLinkToDealWithFavorite(
                        $this->reply['comment_id'], \BlogUser\Model\FavoriteType::COMMENT, isset($this->reply['isFavorite'])) ?>

                    <?php if (isset($this->reply['hasUserReported'])) { ?>
                        <i class="icon icon-flag"></i><?php echo $this->translate('Already Reported') ?>
                    <?php } else { ?>
                        <a href="" class='do-report-on-reply' rel='<?php echo $this->reply['comment_id'] ?>'>
                            <i class="icon-warning-sign"></i><?php echo $this->translate('Make a complaint') ?>
                        </a>
                    <?php } ?>

                    <?php if (isset($this->reply['isHidden'])) { ?>
                        <a href='<?php echo $this->url('unhide-my-blog-content', array('content_type'=>\NBlog\Model\WritingType::COMMENT,'permalink' => $this->reply['comment_id'])) ?>'>
                            <i class="icon-off"></i><?php echo $this->translate('Display again') ?>
                        </a>
                    <?php } else { ?>
                        <a href='<?php echo $this->url('hide-my-blog-content', array('content_type'=>\NBlog\Model\WritingType::COMMENT,'permalink' => $this->reply['comment_id'])) ?>'>
                            <i class="icon-off"></i><?php echo $this->translate('Hide') ?>
                        </a>
                    <?php } ?>
                <?php endif ?>

            <?php else : ?>
                <a href='' class='to-open-login-box'><i class="icon-thumbs-up"></i> <?php echo $this->translate('Make Favorite') ?></a>
                <a href='' class='to-open-login-box'><i class="icon-warning-sign"></i><?php echo $this->translate('Make a complaint') ?></a>
            <?php endif ?>
        </div>
    </div>
    <?php if (!isset($this->reply['hasUserReported'])) : ?>
        <?php echo $this->partial('layout/partials/report-form', array(
            'reportForm' => $this->reportForm,
            'formAction' => $this->url('report'),
            'formId' => $this->reply['comment_id'],
            'reportedOn' => \NBlog\Model\WritingType::COMMENT,
            'idOfReportedOn' => $this->reply['comment_id']
        )) ?>
    <?php endif ?>
</div>