<div class="row-fluid" style="margin-left: 5px;margin-top: 0px;">
    <button id="add-new-profile-pic" style="float: right;" class="btn"><i class="icon-plus"></i>Add New Picture</button>

    <div  id="profile-pic-uploder-box" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel"><?php echo $this->translate("Profile Picture Upload Box.");?></h3>
        </div>
        <div class="modal-body">
            <div class="span24">
                <div class="row-fluid" style="margin-top: 0px;">
                    <div class="auto-crop-resize"></div>
                    <div class="row">
                        <div style="display: none;color: #dc322f;font-weight: 600;"class="span5 message-upload-error">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate("Close");?></button>
<!--            <button class="btn btn-primary">Save changes</button>-->
        </div>
    </div>


</div>
    <div class="row-fluid" style="margin-left: 25px;margin-top: 31px;">
        <?php if($this->isCrop):?>
            <div class="row-fluid">
                <?php if ($this->isFoundImage) : ?>
                    <div class="span6">
                        <div id="crop-holder">
                            <img id="image-id" src="<?php echo $this->imageTempPath; ?><?php echo $this->imageInfo['name']; ?>">
                        </div>
                        <input type="hidden" name="left" value="" id="left-value"/>
                        <input type="hidden" name="top" value="" id="top-value"/>
                        <input type="hidden" name="newWidth" value="" id="newWidth"/>
                        <input type="hidden" name="newHeight" value="" id="newHeight"/>
                    </div>
                    <div class="span15">
                        <div class="row-fluid" style="margin-top: 10px;">
                            <div class="span5">
                                <button id="crop-it" class="btn btn-primary">Crop</button>
                            </div>
                            <div class="span10">
                                <div id="responsive" style="display: none;">
                                    <div class="row">
                                        <div style="float:left;line-height: 32px;" class="span3"> <img style="width: 20px;height: 20px;" src="<?php echo $this->basePath('img/pre-loader.gif') ?>"></div>
                                        <div style="float:left; line-height: 32px;" class="span7"><div id="serverMessage">Loading</div></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                <?php else : ?>
                    <p>
                        <?php $this->translate('No data Found');?>
                    </p>
                <?php endif ?>
            </div>
        <?php else:?>

            <?php if(!empty($this->currentProfilePic)):?>
                <div class="span6">
                    <div class="row">
                        <div>
                            <?php if ($this->objFileHandler->isFileExist("public" . $this->profilePicPath .$this->objFileHandler->renameFile($this->currentProfilePic['name'],true,'profile'))): ?>
                                <a class="gallery" href="<?php echo $this->originalPath.$this->currentProfilePic['name'] ?>">
                                    <img  class="lazy" src="<?php echo $this->basePath('img/grey.gif'); ?>" data-original="<?php echo $this->Image()->albumThumbnail($this->profilePicPath,($this->currentProfilePic['name']),'profile')?>">
                                </a>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
            <?php endif;?>
<!--                <div class="span15">-->
<!--                    <div class="row-fluid" style="margin-top: 0px;">-->
<!--                        <div class="manual-fine-uploader"></div>-->
<!--                        <div class="row">-->
<!--                            <div style="display: none;color: #dc322f;font-weight: 600;"class="span5 message-upload-error">-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

        <?php endif;?>

    </div>






<div id="profile-pic-holder" class="row-fluid">
    <?php if (!empty($this->allProfilePic)): ?>
    <div class="row-fluid">
        <?php foreach ($this->allProfilePic AS $key => $eachPic): ?>
            <?php if ($this->objFileHandler->isFileExist("public" . $this->picViewPath .$this->objFileHandler->renameFile($eachPic['name'],true,'thumb'))): ?>
            <div class="each-profile-photo-holder">
                    <div class="profile-photo">
                        <div class="heading"></div>
                        <a class="gallery" href="<?php echo $this->originalPath.$eachPic['name'] ?>">
                            <img  class="lazy" src="<?php echo $this->basePath('img/grey.gif'); ?>" data-original="<?php echo $this->Image()->albumThumbnail($this->picViewPath,$eachPic['name'])?>">
                        </a>
                        <div class="caption" id="pic-id_<?php echo $eachPic['profile_picture_id']; ?>">
                            <li><a class="delete_pic" href="#"><i class="icon-trash icon-white"></i> মুছে ফেলুন </a></li>
                            <li><a class="add_as_profile_pic" href="#"><i class="icon-cog icon-white"></i> প্রোফাইল ছবি করুন </a></li>
                        </div>
                    </div>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php endif;?>
    </div>

</div>












