
<div class="row-fluid">
    <div class="mail_action_header">
          <span class="header_action">
           <span title="" data-original-title="" class="inbox_back" data-title=" পিছনে যান "><a href="#"><i class="icon-circle-arrow-left"></i>
               </a> </span>
          <span title="" data-original-title="" class="mail_select" data-title="নির্বাচন করুন "><a href="#"><i class="icon-ok-circle"></i> <b class="caret pull-rightp"></b>
              </a> </span>
          <span title="" data-original-title="" class="mail_refresh" data-title="রিফ্রেশ করুন  "><a href="#"><i class="icon-refresh"></i></a> </span>
          <span title="" data-original-title="" class="mail_more" data-title="আরও "><a href="#"><i class="icon-play-circle"></i></a> </span>
      </span>
    <span class="header_delete">
          <span title="" data-original-title="" class="mail_archive" data-title=" সংরক্ষণাগার"><a href="#"><i class="icon-circle-arrow-down"></i>
              </a> </span>
          <span title="" data-original-title="" class="mail_spam_simbol" data-title=" স্প্যাম রিপোর্ট "><a href="#"><i class="icon-exclamation-sign"></i>
              </a> </span>
          <span title="" data-original-title="" class="mail_delete_simbol" data-title="মুছে ফেলুন "><a href="#"><i class="icon-trash"></i>
              </a> </span>
      </span>
      <span class="header_move">
          <span title="" data-original-title="" class="mail_move_to" data-title="
               স্থানান্তর  করুন    "><a href="#"><i class="icon-folder-close"></i>
                  <b class="caret"></b>
              </a>
          </span>
          <span title="" data-original-title="" class="mail_spam_simbol" data-title="চিরকুট"><a href="#"><i class="icon-tags"></i>
                  <b class="caret"></b>
              </a>
          </span>
      </span>
    </div>
</div>

<div class="row-fluid">
    <div class="span24">
    <div class="mail_compose">
        <form class="form-horizontal">
            <div class="control-group">
                <label class="control-label" for="inputEmail"> প্রাপক  : </label>
                <div class="controls">
                    <input class="span24" id="mail-to" autocomplete="off" placeholder=" ইমেইল ঠিকানা " type="text">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputEmail">বিষয়  : </label>
                <div class="controls">
                    <input class="span24" id="inputSubject" placeholder=" বিষয় " type="text">
                </div>
            </div>
            <div class="more control-group">
                <div class="accordion" id="accordion2">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                                আরও  <i class="icon-plus"></i>
                            </a>
                        </div>
                        <div id="collapseTwo" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <div class="control-group">
                                    <label class="control-label" for="inputEmail">Bcc : </label>
                                    <div class="controls">
                                        <input class="span24" id="inputBcc" placeholder="" type="text">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="message_text_area control-group">
                <div class="controls">
                    <textarea class="span24 pull-left" rows="5"></textarea>
                </div>
            </div>

            <div class="message_area_footer">
                <div class="send_mail">
                    <div class="send_mail_button">
                        <button class="btn btn-small btn-primary" type="button"> পাঠিয়ে দিন  </button>
                        <button class="btn btn-small" type="button"> বাতিল করুন  </button>

                        <span class="footer_font"><a href="#"><i class="icon-font"></i></a></span>
                        <span class="footer_file_upload"><i class="icon-file"></i></span>
                        <span class="footer_plus_icon"><a href="#"><i class="icon-plus"></i></a></span>
                    </div>

                </div>

            </div>
        </form>
    </div>
</div>
</div>
