<div class="tile-container static-section col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?php $form = $this->contactForm->setAttribute('action', $this->url('contact-us'))->prepare();
    $formLabel = $this->plugin('formLabel');
    echo $this->form()->openTag($form); ?>
    <div class="set-of-field"><br /></div>

    <div class="set-of-field">
        <?php $reason = $form->get('reason');
        echo $formLabel->openTag($reason) . $this->translate($reason->getLabel()) . $formLabel->closeTag() ?>
        <div>
            <div class="col-sm-10 col-lg-11">
                <?php echo $this->formSelect($reason); ?>
                <span class="field-error"><?php echo implode(' ', $reason->getMessages()) ?></span>
            </div>
        </div>
    </div>

    <div class="set-of-field">
        <?php $subject = $form->get('subject');
        echo $formLabel->openTag($subject) . $this->translate($subject->getLabel()) . $formLabel->closeTag() ?>
        <div>
            <div class="col-sm-10 col-lg-11">
                <?php echo $this->formInput($subject); ?>
                <span class="field-error"><?php echo implode(' ', $subject->getMessages()) ?></span>
            </div>
        </div>
    </div>

    <div class="set-of-field">
        <?php $description = $form->get('description');
        echo $formLabel->openTag($description) . $this->translate($description->getLabel()) . $formLabel->closeTag() ?>
        <div>
            <div class="col-sm-10 col-lg-11">
                <?php echo $this->formTextarea($description); ?>
                <span class="field-error"><?php echo implode(' ', $description->getMessages()) ?></span>
            </div>
        </div>
    </div>

    <div class="set-of-field"><br></div>

    <div class="set-of-field horizontal">
        <label></label>
        <div>
            <script type="text/javascript">
                var RecaptchaOptions = {
                    tabindex: 1,
                    theme: 'custom',
                    custom_theme_widget: 'recaptcha_widget'
                };
            </script>
            <?php $captcha = $form->get('recaptcha_response_field') ?>
            <div id="recaptcha_widget" style="display:none">
                <div id="recaptcha_image"></div>
                <div class="recaptcha_buttons">
                    <a href="javascript:Recaptcha.reload()" title="<?php echo $this->translate('Reload Captcha') ?>"><i class="icon-refresh"></i></a>
                    <a href="javascript:Recaptcha.switch_type('audio')" title="<?php echo $this->translate('Change Captcha Input') ?>"><i class="icon-bullhorn"></i></a>
                </div>
                <?php echo $this->formInput($captcha) ?>
                <span class="field-error"><?php echo implode(' ', $captcha->getMessages()) ?></span>
                <div class="recaptcha_only_if_incorrect_sol" style="color:red"><?php echo $this->formElementErrors($captcha) ?></div>
            </div>
            <script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=6LfH4tkSAAAAAFLE2gpoBZrmyCTRkIp78HjLfWb2"></script>
            <noscript>
                <iframe src="http://www.google.com/recaptcha/api/noscript?k=6LfH4tkSAAAAAFLE2gpoBZrmyCTRkIp78HjLfWb2"
                        height="300" width="500" frameborder="0"></iframe><br />
                <textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
                <input type="hidden" name="<?php echo $captcha->getName() ?>" value="manual_challenge">
            </noscript>
        </div>
    </div>

    <div class="set-of-field">
        <label></label>
        <div>
            <div class="col-sm-10 col-lg-12">
                <div class="radioBox">
                    <div class="checkbox">
                        <?php $agree = $form->get('agree');
                        echo $formLabel->openTag($agree) ?>
                        <?php echo $this->formCheckbox($agree) ?>
                        <i class="icon-"></i><?php echo $this->translate($agree->getLabel()) ?>
                        <span class="field-error"><?php echo implode(' ', $agree->getMessages()) ?></span>
                        <?php echo $formLabel->closeTag() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="set-of-field">
        <label></label>
        <div>
            <div class="col-sm-10 col-lg-12">
                <br />
                <?php echo $this->formSubmit($form->get('submit')); ?>
                <?php echo $this->formButton($form->get('cancel')); ?>
                <?php if (isset($this->showAuthOptions)) : ?>
                <br /><br />
                <?php echo $this->translate('If you have an account') ?>,
                <a href='<?php echo $this->url('login') ?>'><?php echo $this->translate('click here') ?></a><br />
                <?php echo $this->translate('If you forgot password') ?>
                <a href='<?php echo $this->url('forget-password') ?>'><?php echo $this->translate('click here') ?></a>
                <?php endif ?>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
