
<div class="sidebar span6">
  <!--  <?php /*if (!empty($this->categoryLists)) : */?>
    <?php /*echo $this->partial('layout/partials/widget/category_lists', array('categoryLists' => $this->categoryLists)) */?>
    <?php /*endif */?>
    <?php /*if (!empty($this->topBloggers)) : */?>
    <?php /*echo $this->partial('layout/partials/widget/top_posters', array(
        'TopBloggers' => $this->topBloggers, 'professions' => $this->professions )) */?>
    <?php /*endif */?>
    <?php /*if (!empty($this->topCommentPosters)) : */?>
    <?php /*echo $this->partial('layout/partials/widget/top_commenters', array('TopCommentPosters' => $this->topCommentPosters,  'professions' => $this->professions)) */?>
    --><?php //endif ?>

   <!-- <?php /*if (!empty($this->newBloggers)) : */?>
    <?php /*echo $this->partial('layout/partials/widget/new_bloggers', array('NewBloggers' => $this->newBloggers,  'professions' => $this->professions)) */?>
    --><?php //endif ?>

    <?php /*if (!empty($this->blogTrends)) : */?><!--
    <?php /*echo $this->partial('layout/partials/widget/blog_trends', array('blogTrends' => $this->blogTrends)) */?>
    --><?php //endif ?>
</div>