<?php $form = $this->commentForm;
$form->setAttributes(array(
    'action' => $this->url('save-comment',
            array(
                'permalink' => $this->commentOn['permalink'],
                'username'=>'me'
            )
        )
));
$form->prepare();
echo $this->form()->openTag($form) ?>

<?php $element = $form->get('comment') ?>
<?php echo $this->formTextarea($element->setAttribute('id',"comments-reply-".$this->comment['comment_id'])) ?>
<?php echo $this->formElementErrors($element) ?>
    <div class='action-box'>
        <?php $submit = $form->get('submit')->setValue('Write Reply');
        echo $this->formSubmit($submit->setAttribute('class',
            $submit->getAttribute('class').' btn-small'.
            ($this->sessionContainer()->getData('isSmsVerified') ? '' : ' verify-sms')));
        ?>
        <a href="javascript:void(0)"
           class="cancel-commenting btn btn-small"
           rel='<?php echo $this->comment['comment_id'] ?>'>
            <?php echo $this->translate('Cancel') ?>
        </a>
        <?php echo $this->formHidden($form->get('comment_for')->setValue($this->commentFor)) ?>
        <?php echo $this->formHidden($form->get('type')->setValue(\Blog\Model\Comment::TYPE_REPLY)) ?>
        <?php echo $this->formHidden($form->get('parent_id')->setValue($this->comment['comment_id'])) ?>
    </div>
<?php echo $this->form()->closeTag(); ?>