<div class="row">
    <div class="main-container col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="left-column user-search col-xs-12 col-sm-7 col-md-6 col-lg-6">
                <div class="tile col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <?php echo $this->partial('blog/search/user-list', array(
                        'users' => $this->users,
                        'criteria' => $this->criteria,
                        'paginator' => $this->paginatorForUser,
                        'paginatorOptions' => $this->paginatorOptionsForUser
                    )) ?>
                </div><!--    End of tile    -->
            </div><!--  End of mid-column  -->

            <div class="right-column col-xs-12 col-sm-7 col-md-6 col-lg-6">
                <div class="tile col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <?php echo $this->partial('blog/search/post-list', array(
                        'posts' => $this->posts,
                        'categories' => $this->categories,
                        'criteria' => $this->criteria,
                        'paginator' => $this->paginatorForPost,
                        'paginatorOptions' => $this->paginatorOptionsForPost
                    )) ?>
                </div><!--    End of tile    -->
            </div><!--  End of mid-column  -->
        </div>
    </div><!--  End of main-container  -->
</div>